pipeline:
  build:
    image: composer
    commands:
      - composer install
      - cp .env.example .env
      - php artisan key:generate
      - php vendor/bin/phpunit

branches: feature/drone-integration
